"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['gui.py']
DATA_FILES = ['resources/icon.icns']
OPTIONS = {
        'iconfile': 'resources/icon.icns',
        'argv_emulation': True,
        'includes':['sip', 'PyQt5._qt']
        }

setup(
    app=APP,
    name='JParty',
    version="1.0.0",
    author="Stuart Thomas",
    packages="jparty",
    install_requires=['PyQt5'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
