"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
print("TEST")

APP = ['gui.py']
DATA_FILES = ['resources/icon.icns', 'jpardy/icon.png', 'jpardy/loading.gif']
datadir = '/'
DATA_FILES = [(d, [os.path.join(d,f) for f in files])
    for d, folders, files in os.walk(datadir)]

OPTIONS = {
        'iconfile': 'resources/icon.icns',
        'argv_emulation': True,
        'includes':['sip', 'PyQt5._qt']
        }

setup(
    app=APP,
    name='JParty',
    version="1.0.0",
    author="Stuart Thomas",
    packages="jparty",
    install_requires=['PyQt5'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
